### PR TITLE
 Add "file database"

### PR DESCRIPTION
**Pull request by jluims**
Basically a flat file database with entries seperated by \n and fields seperated by spaces

### CODE REVIEW

**Comment by Arcxdd** [comment]
and returning accounts will be 10x harder, thanks

**Comment by Arcxdd** [comment]
i mean honestly its gonna look like an amateur made it if you use something like accounts.txt

please, no 😭😭😭

**Comment by jluims** [comment]
it's just a new db format, it's not default either😭😭😭

**Comment by jluims** [comment]
nvm 😭

**Comment by Arcxdd** [comment]
bro finally realised

**Comment by Arcxdd** [comment]
oh and btw start up discord 🥱🥱

**Pull request closed without merging**
